"""add content column to tasks

Revision ID: 92090468b7b9
Revises: cb38b7fcbc81
Create Date: 2026-04-08 17:27:21.085813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92090468b7b9'
down_revision: Union[str, None] = 'cb38b7fcbc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('content', sa.Text(), nullable=True))
    op.alter_column('tasks', 'file_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('tasks', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tasks', 'file_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('tasks', 'content')
    # ### end Alembic commands ###
